services:
  frontend:
    build:
      context: ../practice-logger-ui
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - VITE_API_URL=http://localhost:5270
    depends_on:
      api:
        condition: service_healthy

  api:
    build:
      context: ../practice-logger-api
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - ASPNETCORE_URLS=http://+:5270
      - ConnectionStrings__PracticeLoggerDb=Host=localhost;Port=5432;Database=PracticeLoggerDb;Username=sa;Password=Password123!
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5270/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:18
    network_mode: host
    environment:
      - POSTGRES_DB=PracticeLoggerDb
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Password123!
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d PracticeLoggerDb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
